spring.application.name=coursmongodb
#spring.data.mongodb.database=springmongodb
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017

#spring.data.mongodb.uri=mongodb://localhost:27017/admin?authSource=admin --username superuser --password motdepasse

spring.data.mongodb.authentication-database=coursmongodbPatrice
spring.data.mongodb.username=
spring.data.mongodb.password=
spring.data.mongodb.database=coursmongodbPatrice
spring.data.mongodb.port=27019
spring.data.mongodb.host=localhost
spring.data.mongodb.uri=mongodb://localhost:27019